# Generated by Django 4.2.2 on 2023-07-24 10:04

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hospital_image', models.ImageField(blank=True, null=True, upload_to='hospitals/profiles', verbose_name='Hospital image')),
                ('hospital_name', models.CharField(max_length=150, verbose_name='Hospital name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='hospital_name', unique=True)),
                ('establish', models.DateField(verbose_name='Establish Date (YYY-MM-DD)')),
                ('address', models.CharField(max_length=150, verbose_name='Hospital Address')),
                ('hospital_about', models.TextField(blank=True, verbose_name='Hospital about')),
                ('telephone_number', models.CharField(max_length=20, verbose_name='Telephone')),
                ('hospital_map', models.CharField(max_length=100, verbose_name='Hospital map')),
                ('hospital_fb', models.CharField(blank=True, max_length=100, verbose_name='Hospital FB')),
                ('hospital_web', models.CharField(blank=True, max_length=100, verbose_name='Hospital Web')),
                ('status', models.BooleanField(default=True, verbose_name='Hospital Status')),
            ],
        ),
        migrations.CreateModel(
            name='MyDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='My doctor status')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital')),
                ('my_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalNews',
            fields=[
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hospitals.hospital')),
                ('news_title', models.CharField(max_length=100, verbose_name='My news')),
                ('news_des', models.CharField(max_length=200, verbose_name='My news description')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='news_title', unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='My news status')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hospitals.hospital')),
                ('service_title', models.CharField(max_length=100, verbose_name='My service')),
                ('service_des', models.CharField(max_length=200, verbose_name='My service description')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='service_title', unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='My service status')),
            ],
        ),
        migrations.CreateModel(
            name='MyDoctorTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20, verbose_name='Day')),
                ('time_from', models.CharField(blank=True, max_length=20, verbose_name='Time from')),
                ('time_to', models.CharField(blank=True, max_length=20, verbose_name='Time to')),
                ('status', models.BooleanField(default=True, verbose_name='Doctor time status')),
                ('my_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.mydoctor')),
            ],
        ),
    ]
