# Generated by Django 4.2.2 on 2023-07-24 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctors/profiles/', verbose_name='Profile image')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, verbose_name='Gender')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth (YYY-MM-DD)')),
                ('specialty', models.CharField(max_length=100, verbose_name='Specialty')),
                ('qualification', models.CharField(max_length=150, verbose_name='Qualification')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Address')),
                ('telephone_number', models.CharField(blank=True, max_length=20, verbose_name='Telephone')),
                ('status', models.BooleanField(default=True, verbose_name='Doctor status')),
            ],
        ),
    ]
